name: Fault Management CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # Testing-kaaga oru temporary database setup panrom
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: fault-mgnt_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin1234
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: pdo_pgsql, pgsql, mbstring, bcmath, xml, zip, intl
          coverage: xdebug 

      # 1. INSTALL
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs

      # 2. MIGRATE & 3. SEED (Inside Test Environment)
      - name: Prepare Test Database
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --force
          php artisan db:seed --force
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: fault-mgnt_test
          DB_USERNAME: postgres
          DB_PASSWORD: admin1234

      # 4. TEST & 5. REPORT
      - name: Run Tests and Report
        run: php artisan test --display-failed-test-details
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: fault-mgnt_test
          DB_USERNAME: postgres
          DB_PASSWORD: admin1234

  deploy:
    #once the test is complete then itll run
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html
            git pull origin master
            composer install --no-interaction --optimize-autoloader --ignore-platform-reqs
            php artisan migrate --force
            php artisan db:seed --force
            php artisan config:cache
            php artisan route:cache
